apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  # AJUSTAR: gerar a URL com o endpoint real do RDS auth-db e a senha final
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BhdXRoLWRiOjU0MzIvYXV0aF9kYj9zc2xtb2RlPXJlcXVpcmU=
  # AJUSTAR: substituir pela chave mestra final usada no auth-service
  MASTER_KEY: bWFzdGVyLWtleS1sb2NhbA==
