apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  # AJUSTAR: substituir pela chave de API real criada no auth-service
  SERVICE_API_KEY: dG1fa2V5XzkwNzhiMWYzNzA1NDE1ZGY2ODUxNzBjMmYyMzJiMjEzOTZkZmIxNTNjM2I0YTllZDYxMGIxNGVkYmQzNWE0Mjg=
