apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  # AJUSTAR: substituir pela chave de API real criada no auth-service
  SERVICE_API_KEY: dG1fa2V5XzVhNTQyOTI2MDljZDViZTQ5M2FkOWZmN2I5Zjc3ZjA2ZTJiNWQ5ZGIxNGE0NjhkNzJkYzFkMDc3YjNjMjU1MzI=
