apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  # AJUSTAR: gerar a URL com o endpoint real do RDS flag-db e a senha final
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjdjMUxudk42REg5YzBPWVlAZmxhZy1kYi5jMGhnMndsemFxdmQudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvZmxhZ19kYj9zc2xtb2RlPXJlcXVpcmU=
