apiVersion: v1
kind: Secret
metadata:
  name: flag-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  # AJUSTAR: gerar a URL com o endpoint real do RDS flag-db e a senha final
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BmbGFnLWRiOjU0MzIvZmxhZ19kYj9zc2xtb2RlPXJlcXVpcmU=
