apiVersion: v1
kind: Secret
metadata:
  name: prod-analytic-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "UkVQTEFDRV9XSVRIX0FXU19BQ0NFU1NfS0VZX0lE"
  AWS_SECRET_ACCESS_KEY: "UkVQTEFDRV9XSVRIX0FXU19TRUNSRVRfQUNDRVNTX0tFWQ=="
  AWS_SESSION_TOKEN: "UkVQTEFDRV9XSVRIX0FXU19TRVNTSU9OX1RPS0VO"
