apiVersion: v1
kind: Secret
metadata:
  name: prod-analytic-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "" # AJUSTAR: substituir pelas credenciais reais em base64 para o ambiente de producao
  AWS_SECRET_ACCESS_KEY: "" # AJUSTAR: substituir pelas credenciais reais em base64 para o ambiente de producao
  AWS_SESSION_TOKEN: "" # AJUSTAR: substituir pelas credenciais reais em base64 para o ambiente de producao
