apiVersion: v1
kind: Secret
metadata:
  name: prod-evaluation-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  SERVICE_API_KEY: "" # AJUSTAR: substituir pelo valor real em base64 para o ambiente de producao
