apiVersion: v1
kind: Secret
metadata:
  name: prod-flag-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  DATABASE_URL: "" # AJUSTAR: substituir pelos valores reais em base64 para o ambiente de producao
