apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-analytics-config
  namespace: tech-challenge-2
data:
  AWS_REGION: us-east-1
  AWS_SQS_URL: "http://sqs:9324/queue/evaluation-events" # AJUSTAR: usar URL real da fila SQS em producao AWS, se este for o ambiente final
  AWS_SQS_ENDPOINT_URL: "http://sqs:9324" # AJUSTAR: remover para AWS real; manter apenas se o ambiente usar SQS local/emulado
  AWS_DYNAMODB_TABLE: ToggleMasterAnalytics
  AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb-local:8000" # AJUSTAR: remover para AWS real; manter apenas se o ambiente usar DynamoDB local/emulado
