apiVersion: v1
kind: Secret
metadata:
  name: dev-analytic-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9jYWw=
  AWS_SECRET_ACCESS_KEY: bG9jYWw=
  AWS_SESSION_TOKEN: bG9jYWw=