apiVersion: v1
kind: Secret
metadata:
  name: dev-auth-secrets
  namespace: tech-challenge-2
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BhdXRoLWRiOjU0MzIvYXV0aF9kYg==
  MASTER_KEY: bWFzdGVyLWtleS1sb2NhbA==