apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-analytics-config
  namespace: tech-challenge-2
data:
  AWS_DYNAMODB_TABLE: ToggleMasterAnalytics
  AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb-local:8000"
