apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-app-config
  namespace: tech-challenge-2
data:
  AWS_REGION: us-east-1
  AWS_SQS_URL: "http://sqs:9324/queue/evaluation-events"
  AWS_SQS_ENDPOINT_URL: "http://sqs:9324"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
