apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: tech-challenge-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: <account-id>.dkr.ecr.<region>.amazonaws.com/flag-service:<tag> #Trocar quando deploy for feito
          # AJUSTAR: substituir pela imagem real do ECR
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prod-flag-secrets
                  key: DATABASE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: prod-app-config
                  key: AUTH_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
